# Generated by Django 5.0.6 on 2024-05-23 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_phone_number', models.CharField(max_length=20, verbose_name='Main Phone Number')),
                ('flowers_text', models.TextField(verbose_name='Flower Text')),
                ('contact_page_back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_page_back_image', to='common.media', verbose_name='Contacts Page Back Image')),
                ('product_page_back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_page_back_image', to='common.media', verbose_name='Product Page Back Image')),
                ('service_page_back_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_page_back_image', to='common.media', verbose_name='Service Page Back Image')),
            ],
            options={
                'verbose_name': 'Common Settings',
                'verbose_name_plural': 'Common Settings',
            },
        ),
    ]
