# Generated by Django 5.0.6 on 2024-05-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Flowers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('occasion', models.CharField(max_length=120, verbose_name='occasion')),
                ('to_whom', models.CharField(max_length=120, verbose_name='to_whom')),
                ('price', models.IntegerField(verbose_name='price')),
                ('desc', models.TextField(verbose_name='desc')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.feedback', verbose_name='feedback')),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowers.tags', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flowers',
            },
        ),
        migrations.CreateModel(
            name='FlowerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.media', verbose_name='image')),
                ('flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flower_image', to='flowers.flowers', verbose_name='flower')),
            ],
            options={
                'verbose_name': 'flower_image',
                'verbose_name_plural': 'flower_images',
            },
        ),
    ]
